[tool.poetry]
name = "sageai"
version = "0.1.1"
description = "File-based functions for ChatGPT's function calling with Pydantic support"
authors = ["Samanimkr <Samanimkr@outlook.com>"]
license = "MIT"
readme = "README.md"
keywords = ["python", "openai", "functions", "chatgpt", "gpt4", "genai"]

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
