[tool.poetry]
name = "sageai"
version = "0.1.2"
description = "File-based functions for ChatGPT's function calling with Pydantic support"
authors = ["Samanimkr <Samanimkr@outlook.com>"]
license = "MIT"
readme = "README.md"
keywords = ["python", "openai", "functions", "chatgpt", "gpt4", "genai"]

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
pydantic = "^2.4.0"
openai = "^0.28.1"
faiss-cpu = "^1.7.4"
numpy = "^1.26.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
